### ISSUE TITLE
Cluster state set to null

### ISSUE THREAD

**Issue by geojaz** [kris-nova/kubicorn#22]
```
erichole   $ kubicorn create -n eric -v 4 -p aws
2017-07-15T13:20:34-06:00 [✔]  Selected [fs] state store
  [~/dev/go/src/github.com/kris-nova/kubicorn]
erichole   $ kubicorn apply -n eric -v 4
2017-07-15T13:20:42-06:00 [✔]  Selected [fs] state store
2017-07-15T13:20:42-06:00 [✔]  Loaded cluster: eric
2017-07-15T13:20:42-06:00 [✔]  Init Cluster
2017-07-15T13:20:42-06:00 [▶]  Running preprocessors: 0x143e350
2017-07-15T13:20:42-06:00 [✔]  Query existing resources
2017-07-15T13:20:42-06:00 [▶]  keypair.Actual
2017-07-15T13:20:42-06:00 [▶]  keypair.Render
2017-07-15T13:20:42-06:00 [▶]  vpc.Actual
2017-07-15T13:20:42-06:00 [▶]  vpc.Render
2017-07-15T13:20:42-06:00 [▶]  internetgateway.Actual
2017-07-15T13:20:42-06:00 [▶]  internetgateway.Render
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Actual
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Render
2017-07-15T13:20:42-06:00 [▶]  subnet.Actual
2017-07-15T13:20:42-06:00 [▶]  subnet.Render
2017-07-15T13:20:42-06:00 [▶]  routetable.Actual
2017-07-15T13:20:42-06:00 [▶]  routetable.Render
2017-07-15T13:20:42-06:00 [▶]  lc.Actual
2017-07-15T13:20:42-06:00 [▶]  lc.Render
2017-07-15T13:20:42-06:00 [▶]  asg.Actual
2017-07-15T13:20:42-06:00 [▶]  asg.Render
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Actual
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Render
2017-07-15T13:20:42-06:00 [▶]  subnet.Actual
2017-07-15T13:20:42-06:00 [▶]  subnet.Render
2017-07-15T13:20:42-06:00 [▶]  routetable.Actual
2017-07-15T13:20:42-06:00 [▶]  routetable.Render
2017-07-15T13:20:42-06:00 [▶]  lc.Actual
2017-07-15T13:20:42-06:00 [▶]  lc.Render
2017-07-15T13:20:42-06:00 [▶]  asg.Actual
2017-07-15T13:20:42-06:00 [▶]  asg.Render
2017-07-15T13:20:42-06:00 [✔]  Resolving expected resources
2017-07-15T13:20:42-06:00 [▶]  keypair.Expected
2017-07-15T13:20:42-06:00 [▶]  keypair.Render
2017-07-15T13:20:42-06:00 [▶]  vpc.Expected
2017-07-15T13:20:42-06:00 [▶]  vpc.Render
2017-07-15T13:20:42-06:00 [▶]  internetgateway.Expected
2017-07-15T13:20:42-06:00 [▶]  internetgateway.Render
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Expected
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Render
2017-07-15T13:20:42-06:00 [▶]  subnet.Expected
2017-07-15T13:20:42-06:00 [▶]  subnet.Render
2017-07-15T13:20:42-06:00 [▶]  routetable.Expected
2017-07-15T13:20:42-06:00 [▶]  routetable.Render
2017-07-15T13:20:42-06:00 [▶]  asg.Expected
2017-07-15T13:20:42-06:00 [▶]  lc.Render
2017-07-15T13:20:42-06:00 [▶]  asg.Expected
2017-07-15T13:20:42-06:00 [▶]  asg.Render
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Expected
2017-07-15T13:20:42-06:00 [▶]  securitygroup.Render
2017-07-15T13:20:42-06:00 [▶]  subnet.Expected
2017-07-15T13:20:42-06:00 [▶]  subnet.Render
2017-07-15T13:20:42-06:00 [▶]  routetable.Expected
2017-07-15T13:20:42-06:00 [▶]  routetable.Render
2017-07-15T13:20:42-06:00 [▶]  asg.Expected
2017-07-15T13:20:42-06:00 [▶]  lc.Render
2017-07-15T13:20:42-06:00 [▶]  asg.Expected
2017-07-15T13:20:42-06:00 [▶]  asg.Render
2017-07-15T13:20:42-06:00 [✔]  Reconciling
2017-07-15T13:20:42-06:00 [▶]  keypair.Expected
2017-07-15T13:20:42-06:00 [▶]  Using keypair subnet [expected]
2017-07-15T13:20:42-06:00 [▶]  keypair.Actual
2017-07-15T13:20:42-06:00 [▶]  Using cached keypair [actual]
2017-07-15T13:20:42-06:00 [▶]  keypair.Apply
2017-07-15T13:20:42-06:00 [▶]  Actual   : 27557f4c4a94a9963a563ef61d2533b0
2017-07-15T13:20:42-06:00 [▶]  Expected : b5242c8ebb4d38869819b9c3c05111ff
2017-07-15T13:20:43-06:00 [✖]  Error during apply! Attempting cleaning: InvalidKeyPair.Duplicate: The keypair 'eric' already exists.
	status code: 400, request id: 6c8fc108-71b6-42cf-afd6-32bb3e2a804e
2017-07-15T13:20:43-06:00 [!]  --------------------------------------
2017-07-15T13:20:43-06:00 [!]  Attempting to delete created resources!
2017-07-15T13:20:43-06:00 [!]  --------------------------------------
2017-07-15T13:20:43-06:00 [✔]  Updating state store for cluster [eric]
  [~/dev/go/src/github.com/kris-nova/kubicorn]
erichole   $ kubicorn apply -n eric -v 4
2017-07-15T13:21:00-06:00 [✔]  Selected [fs] state store
2017-07-15T13:21:00-06:00 [✔]  Loaded cluster:
2017-07-15T13:21:00-06:00 [✔]  Init Cluster
2017-07-15T13:21:00-06:00 [▶]  Running preprocessors: 0x143e350
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x143e37d]

goroutine 1 [running]:
github.com/kris-nova/kubicorn/cluster.ssh(0xc420094dc0, 0x19, 0xc42050fb30, 0x1)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cluster/ssh.go:10 +0x2d
github.com/kris-nova/kubicorn/cluster.InitCluster(0xc420094dc0, 0x12, 0xc42050fc68, 0x1)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cluster/init.go:19 +0xfa
github.com/kris-nova/kubicorn/cmd.RunApply(0x1f9dbc0, 0x17ec080, 0x0)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cmd/apply.go:88 +0x31c
github.com/kris-nova/kubicorn/cmd.glob..func2(0x1f99160, 0xc420141700, 0x0, 0x4)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cmd/apply.go:38 +0x31
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0x1f99160, 0xc420141680, 0x4, 0x4, 0x1f99160, 0xc420141680)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1f999e0, 0xc420010178, 0x0, 0x4)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x1f999e0, 0xc420244000, 0x9ea)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/kris-nova/kubicorn/cmd.Execute()
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cmd/root.go:45 +0x31
main.main()
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/main.go:20 +0x20
```

**Comment by kris-nova** [comment]
Closed in #37
