### ISSUE TITLE
kubicorn panics on apply for DigitalOcean

### ISSUE THREAD

**Issue by bradylove** [kris-nova/kubicorn#501]
I installed kubicorn from master (7bcb550) with `go get` and exported my `DIGITALOCEAN_ACCESS_TOKEN`. When running `kubicorn apply` I am getting a panic for `invalid memory address or nil pointer dereference`.

```
deployments » kubicorn create kobol --profile do                                                                                                                                                                               
2017-12-07T08:15:59-07:00 [ℹ]  Selected [fs] state store
2017-12-07T08:15:59-07:00 [✿]  The state [./_state/kobol/cluster.yaml] has been created. You can edit the file, then run `kubicorn apply kobol`

deployments » kubicorn apply kobo
2017-12-07T08:16:08-07:00 [ℹ]  Selected [fs] state store
2017-12-07T08:16:08-07:00 [ℹ]  Loaded cluster: kobol
2017-12-07T08:16:08-07:00 [ℹ]  Init Cluster
2017-12-07T08:16:08-07:00 [ℹ]  Query existing resources
2017-12-07T08:16:11-07:00 [ℹ]  Resolving expected resources
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x489222]

goroutine 1 [running]:
time.(*Timer).Stop(0x0, 0x11d8c40)
        /home/brady/.asdf/installs/golang/1.9.2/go/src/time/sleep.go:75 +0x22
github.com/kris-nova/kubicorn/cutil/signals.(*Handler).Reset(0xc420290a80)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/cutil/signals/signals.go:73 +0x2f
github.com/kris-nova/kubicorn/cloud.teardown()
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/cloud/atomic_reconciler.go:202 +0x61
github.com/kris-nova/kubicorn/cloud.(*AtomicReconciler).Expected(0xc4202e74a0, 0xc420392820, 0xc4203f01a0, 0x0, 0x0)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/cloud/atomic_reconciler.go:71 +0x33c
github.com/kris-nova/kubicorn/cmd.RunApply(0x19dd540, 0x11d97c0, 0xee5fe0)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/cmd/apply.go:150 +0x6e2
github.com/kris-nova/kubicorn/cmd.ApplyCmd.func1(0xc420256240, 0xc4202790e0, 0x1, 0x1)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/cmd/apply.go:60 +0x72
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc420256240, 0xc4202790a0, 0x1, 0x1, 0xc420256240, 0xc4202790a0)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:653 +0x2a2
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19d6c60, 0xe01219, 0x119c5d9, 0x4)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x19d6c60, 0x0, 0x9bb)
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:687 +0x2b
github.com/kris-nova/kubicorn/cmd.Execute()
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/cmd/root.go:85 +0x31
main.main()
        /home/brady/gocode/src/github.com/kris-nova/kubicorn/main.go:22 +0x20
```

**Comment by xmudrii** [comment]
Hi, thanks for reporting the issue.

This is a known issue and I already submitted PR fixing this (#493). However, I can't merge without @kris-nova, but she's out for Kubecon.

I believe it should be merged soon, but in the meanwhile, you can build of the [`signals-hotfix` branch](https://github.com/kris-nova/kubicorn/tree/signals-hotfix). I'll rebase it right now.

**Comment by xmudrii** [comment]
@bradylove The branch is re-based now, so you can use it in the meanwhile. Thanks once again.

**Comment by bradylove** [comment]
@xmudrii thank you for you quick response.

I rebuilt master with the `-race` flag and tried again, it appeared to work this 
time, however there were 6 data races detected. I pulled the `signals-hotfix` 
branch and also built it with the `-race` flag. Apply worked again and the 
data races still exist.

`kobol apply <cluster name>` from master (7bcb550) see [here](https://gist.github.com/bradylove/d186c51b16e9bf4ad84339db1d0c1c95)
`kobol apply <cluster_name>` from signals-hotfix see [here](https://gist.github.com/bradylove/27936185457c0a445288a4cb354e2261)

I am not too familiar with how the signals package is used but it would seem to me the fix in `singals-hotfix` does fix the panic from a nil pointer but could cause the timer to get out of sync. Example:

* Register is called and starts a go routine.
* Reset is called to stop the timer.
* Go routine starts executing and initializes the timer.

**Comment by xmudrii** [comment]
@bradylove Thank you very much for analysis! This sounds strange.
I'll try to look into it as soon as I can, however I'm quite busy right now.

Signals are being handled from the `cloud` package; the relevant file is [`atomic_reconciler.go`](https://github.com/kris-nova/kubicorn/blob/master/cloud/atomic_reconciler.go).

I believe the problem is that we're creating 4 signal handlers while reconciling, therefore race conditions. I think it would help to use some sort of global signal handler, but as I said, I can't test right now.

Once again, thank you very much for the help. I'll look into it as soon as I can.

**Comment by xmudrii** [comment]
Same happens when you apply cluster without internet connection -- see #503.
