### ISSUE TITLE
nil pointer dereference on kubicorn create

### ISSUE THREAD

**Issue by geojaz** [kris-nova/kubicorn#6]
```
  [~/dev/go/src/github.com/kris-nova/kubicorn]
erichole   $ kubicorn create -n eric
```

```
  [~/dev/go/src/github.com/kris-nova/kubicorn]
erichole   $ kubicorn apply -n eric -v 4
2017-07-15T10:49:27-06:00 [✔]  Selected [fs] state store
2017-07-15T10:49:27-06:00 [✔]  Loaded cluster: eric
2017-07-15T10:49:27-06:00 [✔]  Init Cluster
2017-07-15T10:49:27-06:00 [▶]  Running preprocessors: 0x143d780
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x143d7ad]

goroutine 1 [running]:
github.com/kris-nova/kubicorn/cluster.ssh(0xc420094dc0, 0x19, 0xc420513b30, 0x1)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cluster/ssh.go:10 +0x2d
github.com/kris-nova/kubicorn/cluster.InitCluster(0xc420094dc0, 0x12, 0xc420513c68, 0x1)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cluster/init.go:19 +0xfa
github.com/kris-nova/kubicorn/cmd.RunApply(0x1f96600, 0x17e8400, 0x0)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cmd/apply.go:88 +0x31c
github.com/kris-nova/kubicorn/cmd.glob..func2(0x1f91bc0, 0xc420139940, 0x0, 0x4)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cmd/apply.go:38 +0x31
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0x1f91bc0, 0xc4201398c0, 0x4, 0x4, 0x1f91bc0, 0xc4201398c0)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1f92440, 0xc420010178, 0x0, 0x4)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x1f92440, 0xc42025c000, 0x9ea)
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/kris-nova/kubicorn/cmd.Execute()
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/cmd/root.go:45 +0x31
main.main()
	/Users/erichole/dev/go/src/github.com/kris-nova/kubicorn/main.go:20 +0x20
```

**Comment by geojaz** [comment]
This happens when you try to create a state without specifying a platform

**Comment by geojaz** [comment]
This happens because it defaults to azure which isn't ready to go... closing in favor of implenting azr
