### ISSUE TITLE
Cannot apply OVH 

### ISSUE THREAD

**Issue by licarth** [kris-nova/kubicorn#655]
When trying to apply my OVH config, I get this : 

```
~/p/kubicorn $ kubicorn apply ovh
2018-07-23T12:05:17+02:00 [ℹ]  Selected [fs] state store
2018-07-23T12:05:17+02:00 [ℹ]  Loaded cluster: ovh
2018-07-23T12:05:17+02:00 [ℹ]  Init Cluster
2018-07-23T12:05:17+02:00 [ℹ]  Query existing resources
2018-07-23T12:05:20+02:00 [ℹ]  Resolving expected resources
2018-07-23T12:05:20+02:00 [ℹ]  Reconciling
2018-07-23T12:05:20+02:00 [ℹ]  Using existing KeyPair [ovh]
2018-07-23T12:05:22+02:00 [✔]  Created Network [d0c048f9-ff02-4a51-b801-47407607d28c]
2018-07-23T12:05:23+02:00 [✔]  Created Subnet [bc409b5b-f73b-4793-955b-61ba257ad39f]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x141e888]

goroutine 1 [running]:
github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources.(*Subnet).Apply(0xc4200b62d0, 0x2a12260, 0xc42041a460, 0x2a12260, 0xc42041a4b0, 0xc4201bc2c0, 0x0, 0x2a121a0, 0xc42040b220, 0x0, ...)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/subnet.go:117 +0x388
github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Reconcile(0xc4201c0ee0, 0xc4201bc2c0, 0xc4201bc2c0, 0xc4201bc2c0, 0x0, 0x0)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:119 +0x1ed
github.com/kubicorn/kubicorn/cmd.runApply(0xc42046a6c0, 0x5974f0, 0xc420533ca8)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:145 +0x854
github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc42024a000, 0xc42018ea10, 0x1, 0x1)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:60 +0x6d
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc42024a000, 0xc42018e9d0, 0x1, 0x1, 0xc42024a000, 0xc42018e9d0)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a71360, 0xc420533f60, 0x16860de, 0x1be4b38)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x30e
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x2a71360, 0x0, 0xc4202b7500)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
github.com/kubicorn/kubicorn/cmd.Execute()
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/root.go:76 +0x31
main.main()
	/home/thomas/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20
```

I've tried various versions of kubicorn, and older ones fail for different reasons.
I don't think this is the same problem than those described in other open issues.

Anyone having the same issue ?

**Comment by xmudrii** [comment]
@licarth Hello, thank you so much for reporting the issue!

I can confirm the problem and I'm working on fixing it. It is going little bit slower as I don't have access to OVH, but I will try my best, and will update you once I have some news.

Thank you!

**Comment by xmudrii** [comment]
@licarth I've deployed a fix in #659 that could fix the problem. I don't have access to OVH, so I can't test it.

You need to update to the latest version of `kubicorn` using `git` or `go`, such as:
```
go get -u github.com/kubicorn/kubicorn/...
```

Before applying the cluster, you have to remove the cluster state and create a new one, as there are some changes in the file structure.

If you still have problems, please post the error or stack trace if there is any. If it works for you, let me know, so I can close the issue.

Thank you so much!

**Comment by licarth** [comment]
Hey @xmudrii ! Thank you so much for your quick reaction. I just tried, and I get the following error : 
```
~/p/kubicorn $ kubicorn apply ovh
2018-07-30T15:24:24+02:00 [ℹ]  Selected [fs] state store
2018-07-30T15:24:24+02:00 [ℹ]  Loaded cluster: ovh
2018-07-30T15:24:24+02:00 [ℹ]  Init Cluster
2018-07-30T15:24:25+02:00 [ℹ]  Query existing resources
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x141a937]

goroutine 1 [running]:
c.(*Router).Actual(0xc42052e060, 0xc42041c160, 0x2, 0xc4203bdb38, 0xc42052e3e0, 0x0, 0x0)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/router.go:40 +0xb7
github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Actual(0xc42052e000, 0xc42041c160, 0xc42041c160, 0x0, 0x0)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:50 +0x10a
github.com/kubicorn/kubicorn/cmd.runApply(0xc42034c180, 0x5974f0, 0xc4205e9ca8)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:134 +0x625
github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc42024f8c0, 0xc4201c6070, 0x1, 0x1)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:60 +0x6d
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc42024f8c0, 0xc4201c6030, 0x1, 0x1, 0xc42024f8c0, 0xc4201c6030)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a72360, 0xc4205e9f60, 0x1686e0e, 0x1be5bf8)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x30e
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x2a72360, 0x0, 0xc420405500)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
github.com/kubicorn/kubicorn/cmd.Execute()
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/root.go:76 +0x31
main.main()
	/home/thomas/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20
```

Seems to fail earlier now.

**Comment by xmudrii** [comment]
> Seems to fail earlier now.

I guess this is still a progress. :sweat_smile: 

I've merged #660 which may or may not fix the problem. To get the changes, update kubicorn like described above and recreate the state store file. Then, try to apply the cluster again.

If you get the panics or any other errors again, please post the output here.

Thanks a lot!

**Comment by licarth** [comment]
> I guess this is still a progress.

Clearly it is ! Here is the new stacktrace :) :sweat_smile: 

```
~/p/kubicorn $ kubicorn apply oplaovh
2018-07-30T15:57:24+02:00 [ℹ]  Selected [fs] state store
2018-07-30T15:57:24+02:00 [ℹ]  Loaded cluster: oplaovh
2018-07-30T15:57:24+02:00 [ℹ]  Init Cluster
2018-07-30T15:57:24+02:00 [ℹ]  Query existing resources
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x141a9e5]

goroutine 1 [running]:
github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources.(*Router).Actual(0xc42015cce0, 0xc42013f4a0, 0x2, 0xc4205cb7f8, 0xc42015d120, 0x0, 0x0)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/router.go:40 +0x165
github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Actual(0xc42015cc80, 0xc42013f4a0, 0xc42013f4a0, 0x0, 0x0)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:50 +0x10a
github.com/kubicorn/kubicorn/cmd.runApply(0xc420180180, 0x5974f0, 0xc4204f3ca8)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:134 +0x625
github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc420234fc0, 0xc4202009d0, 0x1, 0x1)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:60 +0x6d
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc420234fc0, 0xc420200990, 0x1, 0x1, 0xc420234fc0, 0xc420200990)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a72360, 0xc4204f3f60, 0x1686e3e, 0x1be5bf8)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x30e
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x2a72360, 0x0, 0xc42031d500)
	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
github.com/kubicorn/kubicorn/cmd.Execute()
	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/root.go:76 +0x31
main.main()
	/home/thomas/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20
```

**Comment by xmudrii** [comment]
@licarth Merged #661. If you can give it a try, let me know does it work for you. Also, if not, stack traces appreciated :wink: 

Thank you so much!

**Comment by licarth** [comment]
When debugging I get `InternetGW:<nil>`.

**Comment by xmudrii** [comment]
In that case, the fix will probably not fix anything for now. I could try to apply another one, but this is getting really ugly. Let's do it anyways :D

**Comment by licarth** [comment]
:unicorn:

**Comment by duythongle** [comment]
> > I guess this is still a progress.
> 
> Clearly it is ! Here is the new stacktrace :) 😅
> 
> ```
> ~/p/kubicorn $ kubicorn apply oplaovh
> 2018-07-30T15:57:24+02:00 [ℹ]  Selected [fs] state store
> 2018-07-30T15:57:24+02:00 [ℹ]  Loaded cluster: oplaovh
> 2018-07-30T15:57:24+02:00 [ℹ]  Init Cluster
> 2018-07-30T15:57:24+02:00 [ℹ]  Query existing resources
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x141a9e5]
> 
> goroutine 1 [running]:
> github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources.(*Router).Actual(0xc42015cce0, 0xc42013f4a0, 0x2, 0xc4205cb7f8, 0xc42015d120, 0x0, 0x0)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/router.go:40 +0x165
> github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Actual(0xc42015cc80, 0xc42013f4a0, 0xc42013f4a0, 0x0, 0x0)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:50 +0x10a
> github.com/kubicorn/kubicorn/cmd.runApply(0xc420180180, 0x5974f0, 0xc4204f3ca8)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:134 +0x625
> github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc420234fc0, 0xc4202009d0, 0x1, 0x1)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:60 +0x6d
> github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc420234fc0, 0xc420200990, 0x1, 0x1, 0xc420234fc0, 0xc420200990)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
> github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a72360, 0xc4204f3f60, 0x1686e3e, 0x1be5bf8)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x30e
> github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x2a72360, 0x0, 0xc42031d500)
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
> github.com/kubicorn/kubicorn/cmd.Execute()
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/cmd/root.go:76 +0x31
> main.main()
> 	/home/thomas/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20
> ```

I can confirm this. Got same issue today

**Comment by moimart1** [comment]
Exactly the problem here, What is the updates ?

**Comment by Xorkle** [comment]
Geting the same issue here. :(

**Comment by anp0** [comment]
just got the same issue, any updates on this?

**Comment by aslafy-z** [comment]
OVH [wasn't supporting](https://community.ovh.com/en/t/openstack-routers-on-ovh/846/2) the OpenStack Router API that kubicorn needed. 

It looks like they are currently trying it, it might already work in some regions. See https://labs.ovh.com/public-cloud-l3-services
